### ISSUE TITLE
Possible to help me with your theme?

### ISSUE THREAD

**Issue by vada-pav** [mikerhodes/nnw-allmine#1]
Hello, I am creating my own theme. I love your theme as well. Could you please show me how to create a theme like yours?
I don’t understand css and hence, cant really figure out your theme.

**Comment by mikerhodes** [comment]
Sorry for taking a while to get back to you!

The best I can give you is https://dx13.co.uk/articles/2024/03/10/tweaking-nnw-theme/, but the CSS tweaks I did were so minimal I can't really give guidance beyond that 😢 .
